### ISSUE TITLE
Extra functions

### ISSUE THREAD

**Issue by slayer** [kulshekhar/fungen#28]
Hi

Thank you for the project, it is very useful

I have a question: What you think about extra helpful functions, like: Detect, Sort, Uniq, etc ? 
Thank you.

**Comment by kulshekhar** [comment]
I'm open to adding new functions. Could you describe how you would expect these to work?

**Comment by kulshekhar** [comment]
Closing for non-activity. Can be opened again should anyone want to continue this discussion.
